format = """
[   ](fg:#ffffff)\

$directory\
\
$git_branch\
$git_status\
$time\
\n$character"""

[directory]
style = "fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#ffffff"
format = '[[ $symbol $branch ]( fg:#ffffff)]($style)'

[git_status]
style = "fg:#ffffff"
format = '[[($all_status$ahead_behind )]( fg:#ffffff)]($style)'

[nodejs]
symbol = ""
style = "bg:#ffffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#ffff)]($style)'

[rust]
symbol = ""
style = "bg:#ffffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#ffffff)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#ffffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#ffffff)]($style)'

[php]
symbol = ""
style = "bg:#ffffff"
format = '[[ $symbol ($version) ](fg:#000000 bg:#ffffff)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#000000 bg:#1d2230)]($style)'

